import { rgb, type Color } from '../art/pixels';

/**
 * Seven original special-stage layouts. Each is the top-left 16x16 quadrant of a
 * 32x32 wrapping grid, mirrored on both axes. Legend:
 *   . empty   B blue sphere   R red sphere   O bumper   Y yellow (spring)   r ring
 * The player starts at the centre (16, 16) facing north.
 */
export interface StageLayout {
  quad: string[];
  floorA: Color;
  floorB: Color;
  skyTop: Color;
  skyBottom: Color;
}

export const STAGES: StageLayout[] = [
  {
    quad: [
      '................',
      '................',
      '..BBBBBBBBB.....',
      '..B.......B.....',
      '..B.rrrrr.B.....',
      '..B.......B.....',
      '..BBBBBBBBB.....',
      '................',
      '..R...R...R.....',
      '................',
      '....BBB....BB...',
      '....BBB....BB...',
      '....BBB.........',
      '..............O.',
      '................',
      '................',
    ],
    floorA: rgb(40, 96, 232),
    floorB: rgb(240, 240, 255),
    skyTop: rgb(16, 24, 96),
    skyBottom: rgb(96, 160, 255),
  },
  {
    quad: [
      '................',
      '.B.B.B.B.B.B.B..',
      '................',
      '.B.RRRRRRRRR.B..',
      '...R.......R....',
      '.B.R.BBBBB.R.B..',
      '...R.B...B.R....',
      '.B.R.B.r.B.R.B..',
      '...R.B...B.R....',
      '.B.R.BBBBB.R.B..',
      '...R.......R....',
      '.B.RRRR.RRRR.B..',
      '................',
      '.B.B.B.B.B.B.B..',
      '..............Y.',
      '................',
    ],
    floorA: rgb(232, 120, 32),
    floorB: rgb(255, 232, 160),
    skyTop: rgb(64, 16, 64),
    skyBottom: rgb(232, 128, 160),
  },
  {
    quad: [
      '................',
      '.BBBB..BBBB.....',
      '.B..B..B..B.....',
      '.B..B..B..B.....',
      '.BBBB..BBBB.....',
      '................',
      '...RRRRRRR......',
      '................',
      '.BBBB..BBBB.....',
      '.B..B..B..B..r..',
      '.B..B..B..B.....',
      '.BBBB..BBBB.....',
      '..............O.',
      '................',
      '...........R....',
      '................',
    ],
    floorA: rgb(48, 176, 72),
    floorB: rgb(224, 255, 200),
    skyTop: rgb(8, 48, 40),
    skyBottom: rgb(96, 208, 176),
  },
  {
    quad: [
      '................',
      '.......B........',
      '......B.B.......',
      '.....B.R.B......',
      '....B.R.R.B.....',
      '...B.R...R.B....',
      '..B.R..r..R.B...',
      '.B.R.......R.B..',
      '..B.R.....R.B...',
      '...B.R...R.B....',
      '....B.R.R.B.....',
      '.....B.R.B......',
      '......B.B.......',
      '.......B.....O..',
      '................',
      '................',
    ],
    floorA: rgb(144, 64, 200),
    floorB: rgb(240, 208, 255),
    skyTop: rgb(24, 8, 56),
    skyBottom: rgb(176, 96, 232),
  },
  {
    quad: [
      '................',
      '..O.O.O.O.O.O...',
      '................',
      '..O.BBBBBBB.O...',
      '....B.....B.....',
      '..O.B.RRR.B.O...',
      '....B.R.R.B.....',
      '..O.B.RrR.B.O...',
      '....B.R.R.B.....',
      '..O.B.R.R.B.O...',
      '....B.....B.....',
      '..O.BBBBBBB.O...',
      '................',
      '..O.O.O.O.O.O...',
      '................',
      '...........Y....',
    ],
    floorA: rgb(208, 40, 64),
    floorB: rgb(255, 200, 200),
    skyTop: rgb(48, 8, 16),
    skyBottom: rgb(232, 112, 96),
  },
  {
    quad: [
      '................',
      '.BRB.BRB.BRB....',
      '.B.B.B.B.B.B....',
      '.BRB.BRB.BRB....',
      '................',
      '.BRB.BRB.BRB....',
      '.B.B.B.B.B.B....',
      '.BRB.BRB.BRB....',
      '................',
      '..rrr...rrr.....',
      '................',
      '...BBBBBBBB.....',
      '...R......R.....',
      '...BBBBBBBB..O..',
      '................',
      '................',
    ],
    floorA: rgb(24, 160, 200),
    floorB: rgb(200, 248, 255),
    skyTop: rgb(8, 32, 64),
    skyBottom: rgb(64, 176, 232),
  },
  {
    quad: [
      '................',
      '.BBBBBBBBBBBBB..',
      '.B...........B..',
      '.B.RRRRRRRRR.B..',
      '.B.R.......R.B..',
      '.B.R.BBBBB.R.B..',
      '.B.R.B...B.R.B..',
      '.B.R.B.O.B.R.B..',
      '.B.R.B...B.R.B..',
      '.B.R.BBBBB.R.B..',
      '.B.R.......R.B..',
      '.B.RRRRR.RRR.B..',
      '.B...........B..',
      '.BBBBBBBBBBBBB..',
      '..............Y.',
      '................',
    ],
    floorA: rgb(96, 96, 112),
    floorB: rgb(232, 232, 240),
    skyTop: rgb(0, 0, 16),
    skyBottom: rgb(80, 80, 128),
  },
];

/** Emerald colours, in stage order. */
export const EMERALD_COLORS: Color[] = [
  rgb(64, 224, 96),
  rgb(232, 64, 64),
  rgb(64, 128, 255),
  rgb(255, 224, 64),
  rgb(224, 96, 232),
  rgb(96, 232, 232),
  rgb(232, 232, 232),
];
